name: commit
on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: deploy staging
        run: echo "deploying to staging..."
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn --frozen-lockfile
      - uses: changesets/action@v1
        id: changesets
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          title: 🏷️ Release changes
          commit: 🏷️ Release changes
          publish: yarn run tag # We need that script in order to add git tag and github release
      - name: deploy production
        if: steps.changesets.outputs.published == 'true'
        run: echo "deploying to production..." # Slap here your own deploy logic